import './scss/app.scss';
import './scss/render-game-screen.scss';
import './scss/change-screen-content.scss';
import './js/bots-list.js';
import './js/questions-list.js';
import './js/render-game-screen.js';
import './js/change-screen-content.js';
import './js/app-logic.js';
import './js/question.js';
